package org.desafio.desafioback.exception;

public class ContatoJaCadastradoException extends RuntimeException {

    public ContatoJaCadastradoException(String message) {
        super(message);
    }
}
